### ISSUE TITLE
Some characters not allowed in name of (host) profile

### ISSUE THREAD

**Issue by pro-sumer** [passepartoutvpn/passepartout-ios#22]
As instructed in the release notes I deleted Passepartout and re-installed 1.0 (1194) from scratch. When adding my host profile for [Encrypt.me](https://encrypt.me) I noticed that I could not use a dot in the profile name (nor a space), while this was possible before.

Is this intentional? If so, why?

(I would like to name this profile "Encrypt.me"; now it's "EncryptMe" because the dot is not allowed)

**Comment by keeshux** [comment]
True, and it is indeed intentional. The reason is that, starting from recent builds, the app stores configuration profiles in separate files. The profile title is used as a filename, therefore I had to get rid of potentially illegal characters for the filesystem.

That said, the dot should be harmless and I might consider re-adding it. FYI the allowed characters are currently:

````
let english = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
let symbols = "-_"
````

**Comment by pro-sumer** [comment]
Can I rename a profile (after that update)? How?

(Or do I need to delete the profile and add it again)

**Comment by keeshux** [comment]
Wait until the next update. Renaming is a convenient feature I already wanted to add and this is a good chance to do it.
